networks:
  innonetwork:

services:
  postgres:
    image: postgres:15.7
    container_name: innoslate-postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - innonetwork
    volumes:
      - innoslatedb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - postgres

  innoslate:
    image: innoslate/innoslate:4.12.1.0
    container_name: innoslate
    networks:
      - innonetwork
    ports:
      - "${CONTAINER_PORT}:8080"
    command: ["innoslate", "run"]
    tty: true
    profiles:
      - innoslate

  innoslate-no-port:
    image: innoslate/innoslate:4.12.1.0
    container_name: innoslate
    networks:
      - innonetwork
    volumes:
      - ./config/server.xml:/usr/local/tomcat/conf/server.xml:z
    command: ["innoslate", "run"]
    tty: true
    profiles:
      - innoslate-no-port

  nginx:
    image: nginx:mainline-alpine3.22-perl
    container_name: innoslate-nginx
    networks:
      - innonetwork
    ports:
      - "${CONTAINER_PORT}:8081"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./nginx-files/certs:/etc/nginx/certs/:z
    profiles:
      - nginx

volumes:
  innoslatedb:
    name: "innoslatedb_volume"